version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: smart_campus_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=smart_campus_optimizer
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
